create table if not exists public.tiktok_videos (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  platform_id bigint not null references public.client_platforms(id) on delete cascade,
  branch_id bigint references public.branches(id) on delete set null,
  video_id text not null,
  video_url text not null,
  description text,
  published_at timestamptz,
  play_count bigint not null default 0 check (play_count >= 0),
  digg_count bigint not null default 0 check (digg_count >= 0),
  comment_count bigint not null default 0 check (comment_count >= 0),
  share_count bigint not null default 0 check (share_count >= 0),
  last_scraped_at timestamptz,
  raw_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (platform_id, video_id)
);

create index if not exists tiktok_videos_client_platform_published_idx
  on public.tiktok_videos (client_id, platform_id, published_at desc);

create index if not exists tiktok_videos_branch_idx
  on public.tiktok_videos (branch_id)
  where branch_id is not null;

alter table public.tiktok_videos enable row level security;

drop policy if exists tiktok_videos_select_own on public.tiktok_videos;
create policy tiktok_videos_select_own
on public.tiktok_videos
for select
to authenticated
using (private.can_access_dashboard(client_id));

revoke all on public.tiktok_videos from public, anon, authenticated;
grant select on public.tiktok_videos to authenticated;
grant all on public.tiktok_videos to service_role;
grant usage, select on sequence public.tiktok_videos_id_seq to service_role;

create or replace view public.unified_feedback
with (security_invoker = true)
as
select
  g.id as source_record_id,
  b.client_id,
  g.branch_id,
  g.platform_id,
  'google_reviews'::text as source_table,
  'google_maps'::text as platform_name,
  g.review_id as external_id,
  g.review_text as feedback_text,
  g.stars::numeric as rating,
  g.review_date as published_at,
  a.sentiment,
  a.category,
  a.severity,
  a.needs_reply,
  a.is_sales_opportunity,
  a.is_complaint,
  a.suggested_reply,
  a.reason,
  a.analysis_summary,
  a.analysis_status,
  g.review_url as source_url
from public.google_reviews g
join public.branches b on b.id = g.branch_id
left join public.feedback_analysis a
  on a.source_table = 'google_reviews' and a.source_record_id = g.id
union all
select
  x.id,
  coalesce(x.client_id, b.client_id, cp.client_id),
  coalesce(x.branch_id, cp.branch_id),
  x.platform_id,
  'x_mentions'::text,
  'x'::text,
  x.tweet_id,
  x.mention_text,
  null::numeric,
  x.posted_at,
  a.sentiment,
  a.category,
  a.severity,
  a.needs_reply,
  a.is_sales_opportunity,
  a.is_complaint,
  a.suggested_reply,
  a.reason,
  a.analysis_summary,
  a.analysis_status,
  x.tweet_url
from public.x_mentions x
left join public.branches b on b.id = x.branch_id
left join public.client_platforms cp on cp.id = x.platform_id
left join public.feedback_analysis a
  on a.source_table = 'x_mentions' and a.source_record_id = x.id
union all
select
  t.id,
  t.client_id,
  coalesce(t.branch_id, cp.branch_id),
  t.platform_id,
  'tiktok_comments'::text,
  'tiktok'::text,
  t.tiktok_comment_id,
  t.comment_text,
  null::numeric,
  t.comment_date,
  a.sentiment,
  a.category,
  a.severity,
  a.needs_reply,
  a.is_sales_opportunity,
  a.is_complaint,
  a.suggested_reply,
  a.reason,
  a.analysis_summary,
  a.analysis_status,
  t.video_url
from public.tiktok_comments t
left join public.client_platforms cp
  on cp.id = t.platform_id and cp.client_id = t.client_id
left join public.feedback_analysis a
  on a.source_table = 'tiktok_comments' and a.source_record_id = t.id
union all
select
  i.id,
  i.client_id,
  coalesce(i.branch_id, cp.branch_id),
  i.platform_id,
  'instagram_comments'::text,
  'instagram'::text,
  i.instagram_comment_id,
  i.comment_text,
  null::numeric,
  i.comment_date,
  a.sentiment,
  a.category,
  a.severity,
  a.needs_reply,
  a.is_sales_opportunity,
  a.is_complaint,
  a.suggested_reply,
  a.reason,
  a.analysis_summary,
  a.analysis_status,
  i.post_url
from public.instagram_comments i
left join public.client_platforms cp
  on cp.id = i.platform_id and cp.client_id = i.client_id
left join public.feedback_analysis a
  on a.source_table = 'instagram_comments' and a.source_record_id = i.id;

revoke all on public.unified_feedback
  from public, anon, authenticated, service_role;
grant select on public.unified_feedback
  to authenticated, service_role;
