create table if not exists public.instagram_posts (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  branch_id bigint references public.branches(id) on delete set null,
  platform_id bigint not null references public.client_platforms(id) on delete cascade,
  post_id text not null,
  post_url text not null,
  media_type text,
  published_at timestamptz,
  last_comment_count integer not null default 0 check (last_comment_count >= 0),
  last_scraped_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instagram_posts_platform_post_key unique (platform_id, post_id)
);

create index if not exists instagram_posts_client_id_idx
  on public.instagram_posts (client_id);

create index if not exists instagram_posts_branch_id_idx
  on public.instagram_posts (branch_id);

create index if not exists instagram_posts_published_at_idx
  on public.instagram_posts (published_at desc);

drop trigger if exists set_instagram_posts_updated_at on public.instagram_posts;
create trigger set_instagram_posts_updated_at
before update on public.instagram_posts
for each row execute function public.set_updated_at();

alter table public.instagram_posts enable row level security;

drop policy if exists instagram_posts_select_own on public.instagram_posts;
create policy instagram_posts_select_own
on public.instagram_posts
for select
to authenticated
using (private.can_access_dashboard(client_id));

revoke all on table public.instagram_posts from anon;
grant select on table public.instagram_posts to authenticated;
grant all on table public.instagram_posts to service_role;
grant usage, select on sequence public.instagram_posts_id_seq to service_role;

create or replace function public.ingest_instagram_post_comments(
  p_client_id bigint,
  p_branch_id bigint,
  p_platform_id bigint,
  p_post_id text,
  p_post_url text,
  p_media_type text,
  p_published_at timestamptz,
  p_comment_count integer,
  p_comments jsonb
)
returns setof public.instagram_comments
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_comment jsonb;
  v_inserted public.instagram_comments%rowtype;
begin
  if p_client_id is null
     or p_platform_id is null
     or nullif(btrim(p_post_id), '') is null
     or nullif(btrim(p_post_url), '') is null then
    raise exception 'invalid_instagram_ingestion_context';
  end if;

  if not exists (
    select 1
    from public.client_platforms cp
    where cp.id = p_platform_id
      and cp.client_id = p_client_id
      and cp.platform_name = 'instagram'
      and cp.is_active is true
      and cp.branch_id is not distinct from p_branch_id
  ) then
    raise exception 'instagram_platform_context_mismatch';
  end if;

  if p_comments is null or jsonb_typeof(p_comments) <> 'array' then
    raise exception 'instagram_comments_must_be_an_array';
  end if;

  insert into public.instagram_posts (
    client_id,
    branch_id,
    platform_id,
    post_id,
    post_url,
    media_type,
    published_at,
    last_comment_count,
    last_scraped_at
  ) values (
    p_client_id,
    p_branch_id,
    p_platform_id,
    btrim(p_post_id),
    btrim(p_post_url),
    nullif(btrim(p_media_type), ''),
    p_published_at,
    greatest(coalesce(p_comment_count, 0), 0),
    now()
  )
  on conflict (platform_id, post_id) do update
  set client_id = excluded.client_id,
      branch_id = excluded.branch_id,
      post_url = excluded.post_url,
      media_type = excluded.media_type,
      published_at = excluded.published_at,
      last_comment_count = greatest(
        public.instagram_posts.last_comment_count,
        excluded.last_comment_count
      ),
      last_scraped_at = excluded.last_scraped_at;

  for v_comment in
    select value
    from jsonb_array_elements(p_comments)
  loop
    if nullif(btrim(v_comment ->> 'comment_id'), '') is null
       or nullif(btrim(v_comment ->> 'comment_text'), '') is null then
      continue;
    end if;

    insert into public.instagram_comments (
      client_id,
      branch_id,
      platform_id,
      post_url,
      instagram_comment_id,
      commenter_username,
      comment_text,
      comment_date,
      like_count,
      is_reply,
      reply_to_comment_id,
      is_author_reply,
      media_id,
      analysis_status,
      raw_data,
      updated_at
    ) values (
      p_client_id,
      p_branch_id,
      p_platform_id,
      p_post_url,
      btrim(v_comment ->> 'comment_id'),
      nullif(btrim(v_comment ->> 'commenter_username'), ''),
      btrim(v_comment ->> 'comment_text'),
      case
        when nullif(v_comment ->> 'comment_date', '') is null then null
        else ((v_comment ->> 'comment_date')::timestamptz at time zone 'UTC')
      end,
      greatest(coalesce((v_comment ->> 'like_count')::integer, 0), 0),
      coalesce((v_comment ->> 'is_reply')::boolean, false),
      nullif(btrim(v_comment ->> 'reply_to_comment_id'), ''),
      coalesce((v_comment ->> 'is_author_reply')::boolean, false),
      p_post_id,
      'pending',
      v_comment -> 'raw_data',
      now()
    )
    on conflict (platform_id, instagram_comment_id) do nothing
    returning * into v_inserted;

    if found then
      return next v_inserted;
    end if;
  end loop;

  update public.client_platforms
  set last_sync_at = now(),
      last_success_at = now(),
      last_error = null,
      connection_status = 'connected',
      updated_at = now()
  where id = p_platform_id;

  return;
end;
$$;

revoke all on function public.ingest_instagram_post_comments(
  bigint,
  bigint,
  bigint,
  text,
  text,
  text,
  timestamptz,
  integer,
  jsonb
) from public, anon, authenticated;

grant execute on function public.ingest_instagram_post_comments(
  bigint,
  bigint,
  bigint,
  text,
  text,
  text,
  timestamptz,
  integer,
  jsonb
) to service_role;
